### ISSUE TITLE
Zoom into alternate image

### ISSUE THREAD

**Issue by lunetics** [sparanoid/lightense-images#1]
I played around with your lib, simple and small, i like it.

Now, when i use a thumbail e.g. `<img src="/path/to/thumbnail_small.png" data-image="/path/to/full_res_image.png" >` and use lightense, it will just zoom in the thumb (but with the size of the data-img).

Wheni use the "data-image" attribute 2 things happen:
- on click, it will be zoomed in by the size of the "data-image", but still the src is display (blurry big thumb)
- on ctrl click (new window), the full size image will be shown.

Is that considered a bug?

**Comment by 3runoDesign** [comment]
@lunetics hi... see this test i did.
[Progressive loading placeholde](http://codepen.io/3runoDesign/pen/xORQjR/)

**Comment by sparanoid** [comment]
@lunetics to keep things simple, I think it's better to handle "lazy load" feature separately, @3runoDesign's implementation is a good approach.

> Wheni use the "data-image" attribute 2 things happen:

I've fixed these bugs in v1.0.2.
