### ISSUE TITLE
Doesn't play well with prior transforms 

### ISSUE THREAD

**Issue by rejas** [sparanoid/lightense-images#14]
Just adding one line to the demo doesnt make the lightbox appear, see my fork of your codepen: https://codepen.io/rejas/pen/WpjKqQ

Adding a rotation to the surrounding paragraph results in a "blank" overlay appearing but nothing more. I'm out of ideas myself how or if this can be fixed or resolved, maybe you have?

**Comment by sparanoid** [comment]
Hi @rejas, you can apply rotate transform on images to resolve this issue, see demo:

https://codepen.io/sparanoid/pen/oZwXgv

**Comment by rejas** [comment]
Thanks for the reply but can't do your solution on my site i guess without more hacks :-( My images are inside figures that are rotated (see example at https://veeck.de/travel_03_ind.html). Any idea where I have to look to maybe help you fix it in your code?
