### ISSUE TITLE
Transformation cause image getting blurry

### ISSUE THREAD

**Issue by radiocity** [sparanoid/lightense-images#31]
[image-rendering](https://css-tricks.com/almanac/properties/i/image-rendering/) could help

**Comment by sparanoid** [comment]
Can you give me a demo link to reproduce this issue? Thanks.

**Comment by radiocity** [comment]
Here comes [Demo](https://jsfiddle.net/9prv2wmy/)
Google Chrome 63.0.3239.132 (x64)

![demo](https://user-images.githubusercontent.com/2347073/34716503-1ad58dc6-f541-11e7-883a-570ed6f5053c.gif)

**Comment by sparanoid** [comment]
This seems like an OS related issue, I cannot reproduce this on macOS:

Original:

![image](https://user-images.githubusercontent.com/96356/35254859-17e31124-0027-11e8-8d81-5ac997155691.png)

Zoomed:

![image](https://user-images.githubusercontent.com/96356/35254844-02a3085a-0027-11e8-92af-4cb2848b8cb3.png)

If you're not comfortable with the default CSS applied, you can always customize the appearance on your own:

```css
img {
  image-rendering: pixelated;
}
```

**Comment by radiocity** [comment]
Nope. After couple tests it became obvious that image-rendering doesn`t affect on thin lines.  
Replace traslate3d with absolute positioning to prevent blurry effect

**Comment by bencorlett** [comment]
I can reproduce (and fix) this issue.

It appears that the `translate3d` property causes images to render blurry in Chrome and Safari (I haven't tested other browsers) when offsetting by a percentage of a pixel. Rounding to the nearest pixel fixes this issue completely.

Here's an example of the blurry (as-is currently) image:

![screen shot 2018-05-09 at 12 10 14 pm](https://user-images.githubusercontent.com/181919/39792327-689be122-5383-11e8-9427-c2390bbb6604.png)

Here's that same image with the `translate3d` property rounded off, and you'll notice if you open the image that the text on the image is considerably clearer:

![screen shot 2018-05-09 at 12 10 05 pm](https://user-images.githubusercontent.com/181919/39792352-822ba974-5383-11e8-8b6d-432327ed205e.png)

I'm happy to submit a PR to fix this - let me know.

**Comment by nmtrung** [comment]
@sparanoid Can you fix that?

**Comment by sparanoid** [comment]
Sorry for the late reply, just fixed it and released a new version.
