### ISSUE TITLE
how to destroy Lightense ?

### ISSUE THREAD

**Issue by sadeghbarati** [sparanoid/lightense-images#34]
@sparanoid 

thanks for your great plugin <3

i have `smooth-page-transition` with Barba.js

i have to `reinit` the plugin.. 

reinit the plugin after page change but 

that backdrop clone three time after page changed 

and image transfrom does'nt work good 

pls tell me how to `destory` plugin and `remove` backdrops

Regards

**Comment by sparanoid** [comment]
@riiccardo to make things simple, just fix it by checking if an images already inited.
