### ISSUE TITLE
Image is not displayed correctly when placed inside an element with overflow:auto

### ISSUE THREAD

**Issue by warstellar** [sparanoid/lightense-images#45]
I have created a sample document that shows the behaviour:
[!html example.zip](https://github.com/sparanoid/lightense-images/files/4146751/html.example.zip)

The problem: if one of lightense image parents has overflow:auto, the image is not positioned correctly, and is obscured.

**Comment by sparanoid** [comment]
This is the expected behavior because zoomed images are just inside the `overflow: auto` parent without copying to an outside node for better performance.
